services:
  app:
    build: .
    container_name: quizergo_backend
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: quizergo_redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    command: -["redis-server", "--requirepass", "password"]
      -["redis-server", "--appendonly", "yes"]

    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: quizergo_postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
